export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const FILTER_TASKS = "FILTER_TASKS";
export const TOGGLE_COMPLETED_TASK = "TOGGLE_COMPLETED_TASK";
